### ISSUE TITLE
build problem, classes are unknown

### ISSUE THREAD

**Issue by nielsboldt** [amplab/spark-indexedrdd#11]
I have problems including indexedrdd into a project and compile it. While compiling I get errors like

[info] Compiling 4 Scala sources to C:\temp\boldt-spark\target\scala-2.10\test-c
lasses...
[error] C:\temp\boldt-spark\src\test\scala\edu\berkeley\cs\amplab\spark\indexedrdd\KeySerializerSuite.scala:53: not found: type Tuple2Serializer
[error]     val ser = new Tuple2Serializer[A, B]()(aSer, bSer)
[error]                   ^
[error] one error found
[error](test:compile) Compilation failed
[error] Total time: 5 s, completed 22-09-2015 15:53:52

All classes seems to be invisible even that the jar(spark-indexedrdd) is on the classpath

I created a fork and removed the sources and instead inserted a dependency on the spark-indexedrdd jar, so basically you should be able to recreate the error by running "sbt test" on the following https://github.com/amplab/spark-indexedrdd/pull/10

**Comment by nielsboldt** [comment]
Case dismissed - I apparently can't distinguish between Rdd and RDD

**Comment by vipulvj** [comment]
Hi ... can indexed RDD used for java as well. Can u please provide me a code sample for the same.
