### ISSUE TITLE
Tuple2[String, String] as the key, but no such KeySerializer[(String, String)]

### ISSUE THREAD

**Issue by hywUMD** [amplab/spark-indexedrdd#9]
Hi All, 

I am trying to create an IndexedRDD from RDD[(String, String)], but it seems that the KeySerializer does not provide a serialization function for Tuple2[String, String]. Is there anyway to work around this? Or how should I use an alternative KeySerializer?

Thanks,
Hong

**Comment by hywUMD** [comment]
Never mind. You can insert a special character like "$" between the pair items to form a new String as the key!

**Comment by ankurdave** [comment]
That would work. I also added a new serializer for pairs in 134c3a190649a39fd516d87a7b6c3cfe80cb4ba8.

**Comment by hywUMD** [comment]
@ankurdave Thanks for your work!
